server {
    listen 80 default_server;
    server_name _;

    # Allow IP access on HTTP
    root /var/www/personal-site;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name ken-portfolio.duckdns.org;
    # Redirect HTTP domain to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ken-portfolio.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/ken-portfolio.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ken-portfolio.duckdns.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/personal-site;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
